---
# tasks file for easy_rsa

- name: Install easy-rsa packages
  become: yes
  apt:
    name: "{{ easy_rsa_packages }}"
    state: latest
    cache_valid_time: 86400
  tags:
    - easy_rsa

- name: Create CA directory
  become: yes
  command: make-cadir {{ easy_rsa_ca_dir }}
  args:
    creates: "{{ easy_rsa_ca_dir }}"
  tags:
    - easy_rsa

- name: Create keys directory
  become: yes
  file:
    path: "{{ easy_rsa_key_dir }}"
    owner: root
    group: root
    mode: 0700
    state: directory
  tags:
    - easy_rsa

- name: Create vars configuration file
  become: yes
  template:
    src: vars.j2
    dest: "{{ easy_rsa_ca_dir }}/vars"
    owner: root
    group: root
    mode: 0644
  tags:
    - easy_rsa

- name: Prep the keys directory
  become: yes
  shell: ". ./vars; ./clean-all >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/index.txt"
  tags:
    - easy_rsa

- name: Generate Diffie-Hellman parameters
  become: yes
  shell: ". ./vars; ./build-dh >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/dh{{ easy_rsa_key_size }}.pem"
  tags:
    - easy_rsa

- name: Build CA
  become: yes
  shell: ". ./vars; ./pkitool --initca >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/ca.key"
  tags:
    - easy_rsa

- name: Generate server certificate and key
  become: yes
  shell: ". ./vars; ./pkitool --server {{ easy_rsa_key_name }} >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/{{ easy_rsa_key_name }}.key"
  tags:
    - easy_rsa

- name: Generate client certificates and keys
  become: yes
  shell: ". ./vars; ./pkitool {{ item }} >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/{{ item }}.key"
  with_items:
    - "{{ easy_rsa_clients }}"
  tags:
    - easy_rsa
